// Regenerates src/lib/zips/data/zcta-centroids.ts from the US Census ZCTA
// gazetteer (public domain). Run once when refreshing the bundled ZIP dataset:
//
//   node scripts/build-zcta.mjs
//
// It downloads the national ZCTA gazetteer, extracts the 5-digit ZCTA (GEOID)
// and its internal-point centroid (INTPTLAT/INTPTLONG), and writes a compact
// packed string consumed by src/lib/zips/store.ts. The data module is
// server-only (never imported by client components) so its size never reaches
// the browser bundle.
import { execSync } from "node:child_process"
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const YEAR = process.env.ZCTA_YEAR ?? "2023"
const URL = `https://www2.census.gov/geo/docs/maps-data/data/gazetteer/${YEAR}_Gazetteer/${YEAR}_Gaz_zcta_national.zip`
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "zips",
  "data",
  "zcta-centroids.ts",
)

// Allow `node scripts/build-zcta.mjs /path/to/already_extracted.txt` for offline runs.
let txtPath = process.argv[2]
if (!txtPath) {
  const dir = mkdtempSync(join(tmpdir(), "zcta-"))
  console.log(`Downloading ${URL}`)
  execSync(`curl -fsSL -o "${join(dir, "z.zip")}" "${URL}"`, { stdio: "inherit" })
  execSync(`unzip -o "${join(dir, "z.zip")}" -d "${dir}"`, { stdio: "ignore" })
  txtPath = join(dir, readdirSync(dir).find((f) => f.endsWith(".txt")))
}

const lines = readFileSync(txtPath, "utf8").split(/\r?\n/)
const rows = []
for (let i = 1; i < lines.length; i++) {
  const line = lines[i]
  if (!line.trim()) continue
  const cols = line.split("\t")
  const zip = cols[0]?.trim()
  const lat = Number(cols[5]?.trim())
  const lng = Number(cols[6]?.trim())
  if (!zip || zip.length !== 5 || Number.isNaN(lat) || Number.isNaN(lng)) continue
  // 4 decimals ≈ 11m — far finer than any storm polygon needs.
  rows.push(`${zip},${lat.toFixed(4)},${lng.toFixed(4)}`)
}
rows.sort()

const packed = rows.join(";")
const file = `// AUTO-GENERATED by scripts/build-zcta.mjs from the ${YEAR} US Census ZCTA
// gazetteer (public domain). Do not edit by hand — rerun the script to refresh.
// Format: semicolon-separated rows of "zip,lat,lng". ${rows.length} ZCTAs.
/* eslint-disable */
export const ZCTA_PACKED =
  ${JSON.stringify(packed)}
`
writeFileSync(OUT, file)
console.log(`Wrote ${rows.length} ZCTAs → ${OUT} (${(file.length / 1024).toFixed(0)} KB)`)
